import { validatePublicConnectionResource } from "./connectionsModel.js";

// Development-only examples. These are fictional and are never written to Supabase.
const fixtureSources = [
  {
    slug: "prairie-learning-collective",
    name: "Prairie Learning Collective",
    short_description: "A fictional weekly learning community for Central Illinois homeschool families.",
    description: "Sample cooperative classes, family gatherings and hands-on learning for a broad range of ages.",
    worldview: "christian",
    worldview_details: "Christian",
    age_min: 6,
    age_max: 17,
    grade_min: "1",
    grade_max: "12",
    age_grade_notes: "Family activities include younger siblings.",
    delivery_mode: "in_person",
    accepting_status: "accepting",
    cost_type: "paid",
    homeschool_specific: true,
    daytime_available: true,
    homeschool_discount: false,
    service_area_summary: "Peoria and nearby communities",
    visibility: "public",
    last_verified_on: "2026-07-18",
    primary_category_slug: "co-ops-groups-community",
    primary_category_name: "Co-ops, Groups & Community",
    primary_city: "Peoria",
    primary_county: "Peoria",
    category_slugs: ["co-ops-groups-community", "classes-tutors-academic-support"],
    tag_slugs: ["christian", "daytime", "teen"],
    updated_at: "2026-07-18T12:00:00Z",
    locations: [{
      name: "Peoria meeting site",
      location_kind: "program_site",
      address_line_1: "",
      address_line_2: "",
      city: "Peoria",
      county: "Peoria",
      state: "IL",
      postal_code: "",
      service_area: "Peoria County",
      is_primary: true,
      sort_order: 0,
    }],
    contacts: [{ location_name: "", kind: "website", label: "Program website", value: "https://example.com/prairie-learning", sort_order: 0 }],
  },
  {
    slug: "heartland-arts-workshop",
    name: "Heartland Arts Workshop",
    short_description: "A fictional daytime arts program offering small-group instruction.",
    description: "Sample drawing, ceramics and mixed-media workshops with options for elementary and teen learners.",
    worldview: "no_stated_affiliation",
    worldview_details: "No stated religious affiliation",
    age_min: 8,
    age_max: 18,
    grade_min: "3",
    grade_max: "12",
    age_grade_notes: "Class prerequisites vary.",
    delivery_mode: "hybrid",
    accepting_status: "waitlist",
    cost_type: "variable",
    homeschool_specific: true,
    daytime_available: true,
    homeschool_discount: true,
    service_area_summary: "Bloomington-Normal and online",
    visibility: "limited",
    last_verified_on: "2026-06-02",
    primary_category_slug: "arts-music-enrichment",
    primary_category_name: "Arts, Music & Enrichment",
    primary_city: "Normal",
    primary_county: "McLean",
    category_slugs: ["arts-music-enrichment"],
    tag_slugs: ["daytime", "online", "teen"],
    updated_at: "2026-06-02T12:00:00Z",
    locations: [{
      name: "Normal area",
      location_kind: "service_area",
      address_line_1: "",
      address_line_2: "",
      city: "Normal",
      county: "McLean",
      state: "IL",
      postal_code: "",
      service_area: "Bloomington-Normal",
      is_primary: true,
      sort_order: 0,
    }],
    contacts: [{ location_name: "", kind: "website", label: "General information", value: "https://example.com/heartland-arts", sort_order: 0 }],
  },
  {
    slug: "central-illinois-family-support",
    name: "Central Illinois Family Support",
    short_description: "A fictional traveling family-support and consultation resource.",
    description: "Sample consultations and parent education offered throughout the central Illinois corridor.",
    worldview: "information_not_provided",
    worldview_details: "Information not provided",
    age_min: null,
    age_max: null,
    grade_min: "",
    grade_max: "",
    age_grade_notes: "Serves families across age ranges.",
    delivery_mode: "traveling",
    accepting_status: "contact_for_availability",
    cost_type: "variable",
    homeschool_specific: false,
    daytime_available: true,
    homeschool_discount: false,
    service_area_summary: "Woodford, Tazewell and Fulton counties",
    visibility: "limited",
    last_verified_on: "2026-05-14",
    primary_category_slug: "special-needs-therapy-family-support",
    primary_category_name: "Special Needs, Therapy & Family Support",
    primary_city: "Goodfield",
    primary_county: "Woodford",
    category_slugs: ["special-needs-therapy-family-support"],
    tag_slugs: ["daytime", "traveling"],
    updated_at: "2026-05-14T12:00:00Z",
    locations: [{
      name: "Regional service area",
      location_kind: "service_area",
      address_line_1: "",
      address_line_2: "",
      city: "Goodfield",
      county: "Woodford",
      state: "IL",
      postal_code: "",
      service_area: "Woodford, Tazewell and Fulton counties",
      is_primary: true,
      sort_order: 0,
    }],
    contacts: [],
  },
];

export const connectionFixtures = Object.freeze(fixtureSources.map(validatePublicConnectionResource));
