alter table public.items
add column if not exists item_type text not null default 'individual',
add column if not exists bundle_piece_count integer not null default 0;

alter table public.items
drop constraint if exists items_item_type_valid;

alter table public.items
add constraint items_item_type_valid
check (item_type in ('individual', 'bundle'));

alter table public.items
drop constraint if exists items_bundle_piece_count_nonnegative;

alter table public.items
add constraint items_bundle_piece_count_nonnegative
check (bundle_piece_count >= 0);

create table if not exists public.bundle_components (
  id bigint generated by default as identity primary key,
  bundle_item_id text not null,
  component_item_id text not null,
  piece_quantity integer not null default 1 check (piece_quantity > 0),
  created_at timestamptz not null default now(),
  unique (bundle_item_id, component_item_id),
  check (bundle_item_id <> component_item_id)
);

create index if not exists bundle_components_bundle_item_idx
on public.bundle_components (bundle_item_id);

create index if not exists bundle_components_component_item_idx
on public.bundle_components (component_item_id);

alter table public.bundle_components enable row level security;

drop policy if exists "bundle components active staff manage" on public.bundle_components;
create policy "bundle components active staff manage"
on public.bundle_components for all to authenticated
using (public.current_profile_is_active())
with check (public.current_profile_is_active());

grant select, insert, update, delete on public.bundle_components to authenticated;
grant usage, select on sequence public.bundle_components_id_seq to authenticated;

create sequence if not exists public.inventory_sku_seq;

select setval(
  'public.inventory_sku_seq',
  greatest(
    coalesce(
      (
        select max((substring(sku from '([0-9]+)$'))::bigint)
        from public.items
        where sku ~ '[0-9]+$'
      ),
      0
    ),
    1
  ),
  exists (select 1 from public.items where sku ~ '[0-9]+$')
);

create or replace function public.next_inventory_sku(p_item_type text default 'individual')
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  next_number bigint;
  sku_prefix text;
begin
  if not public.current_profile_is_active() then
    raise exception 'An active staff account is required.';
  end if;

  if p_item_type not in ('individual', 'bundle') then
    raise exception 'Unsupported inventory item type.';
  end if;

  sku_prefix := case when p_item_type = 'bundle' then 'ILHRC-B-' else 'ILHRC-' end;

  loop
    next_number := nextval('public.inventory_sku_seq');
    if not exists (
      select 1
      from public.items
      where sku = sku_prefix || lpad(next_number::text, 6, '0')
    ) then
      return sku_prefix || lpad(next_number::text, 6, '0');
    end if;
  end loop;
end
$$;

revoke all on function public.next_inventory_sku(text) from public;
grant execute on function public.next_inventory_sku(text) to authenticated;

create or replace function public.cleanup_item_bundle_links()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.bundle_components
  where bundle_item_id = old.id::text
     or component_item_id = old.id::text;
  return old;
end
$$;

drop trigger if exists items_cleanup_bundle_links on public.items;
create trigger items_cleanup_bundle_links
before delete on public.items
for each row execute function public.cleanup_item_bundle_links();

create or replace view public.public_catalog_items as
select
  item.id,
  item.title,
  item.curriculum,
  item.subject,
  item.grade_level,
  item.category,
  item.edition,
  item.isbn,
  item.final_price,
  greatest(item.quantity::integer - coalesce(reservation.active_count, 0), 0)::smallint as quantity,
  item.image_url,
  item.created_at,
  item.item_type,
  item.bundle_piece_count,
  case
    when item.item_type = 'bundle' then array(
      select
        component.piece_quantity::text || '× ' || coalesce(component_item.title, 'Untitled item')
      from public.bundle_components component
      join public.items component_item
        on component_item.id::text = component.component_item_id
      where component.bundle_item_id = item.id::text
      order by component.id
    )
    else array[]::text[]
  end as bundle_contents
from public.items item
left join lateral (
  select count(*)::integer as active_count
  from public.book_reservations
  where item_id = item.id::text
    and status in ('pending', 'ready')
    and expires_at > now()
) reservation on true
where coalesce(item.status, 'Available') = 'Available'
  and coalesce(item.public_visible, true) = true
  and coalesce(item.quantity, 0) > 0;

grant select on public.public_catalog_items to anon, authenticated;

notify pgrst, 'reload schema';
